---
title: Bestuur een verkeerslicht met Scratch 2
hero_image: images / banner.png
description: Leer een verkeerslicht te besturen en te coderen met behulp van Scratch 2
listed: false
copyedit: false
version: 3
last_tested: 2018/11/20
steps:
  - 
    title: Inleiding
  - 
    title: De LEDs aansluiten
  - 
    title: De LED's aansturen
  - 
    title: Volgorde verkeerslichten
