---
title: Traffic Lights with Scratch 2
hero_image: images/banner.png
description: ट्रैफिक लाइट एल. ई. डी. को नियंत्रित करने और Scratch 2 का उपयोग करके ट्रैफिक लाइट अनुक्रम को नियंत्रित करने के बारे में जानें
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: भूमिका
  - 
    title: Connect the LEDs
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
