---
title: Control a Traffic Lights Sequence with Scratch 2
hero_image: images/banner.png
description: スクラッチ2を使用して信号機のLEDを制御し、信号機のシーケンスをコードする方法を学ぶ
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: LEDを接続する
  - 
    title: LEDの制御
