---
title: Traffic Lights with Scratch 2
hero_image: images/banner.png
description: آموزش کنترل LEDهای چراغ راهنمایی و کدنویسی آن با استفاده از Scratch 2
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: مقدمه
  - 
    title: LEDها را وصل کنید
  - 
    title: Control the LEDs
  - 
    title: Traffic lights sequence
