---
title: Steuere eine Verkehrsampel mit Scratch 2
hero_image: images/banner.png
description: Lerne die LEDs einer Verkehrs-Ampel steuern und einen Ampelablauf mit Scratch 2 zu programmieren
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components, scratch
site_areas: jam
hardware: electronic-components
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
-
title: Einleitung
-
title: Was du brauchen wirst
-
title: Die LEDs anschließen
-
title: Die LEDs steuern
-
title: Ampel Sequenz