---
title: Steuere eine Verkehrsampel mit Scratch 2
hero_image: images/banner.png
description: Lerne die LEDs einer Verkehrs-Ampel steuern und einen Ampelablauf mit Scratch 2 zu programmieren
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - title: Einleitung
  - title: Verbinde die LEDs (Leuchdioden)
  - title: Steuere die LEDs (Leuchtdioden)
  - title: Eine Verkehrsampel steuern
