---
title: Steuere eine Verkehrsampel mit Scratch 2
hero_image: images/banner.png
description: Lerne die LEDs einer Verkehrs-Ampel steuern und einen Ampelablauf mit Scratch 2 zu programmieren
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Die LEDs anschließen
  - 
    title: Die LEDs steuern
