---
title: Közlekedési lámpák vezérlése Scratch 2 segítségével
hero_image: images/banner.png
description: Tanuld meg, hogy vezéreld a jelzőlámpákat és kódolj egy közlekedési lámpa ciklust a Scratch 2 segítségével
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - 
    title: Bevezető
  - 
    title: Csatlakoztasd a LED-eket
  - 
    title: Vezéreld a LED-eket
  - 
    title: Közlekedési lámpák ciklusa
