---
title: Contrôler une Séquence de Feux de Circulation avec Scratch 2
hero_image: images/banner.png
description: Apprenez à contrôler les LEDs du feu et à coder une séquence de feux de circulation à l'aide de Scratch 2
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont vous aurez besoin
  - 
    title: Connectez les LED
  - 
    title: Contrôlez les LED
