---
title: Controlla un semaforo con Scratch 2
hero_image: images/banner.png
description: Impara a controllare un semaforo a LED e a programmare una sequenza di luci con Scratch 2
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Collegare i LED
  - 
    title: Controllare i LED
